########Input R parameters(TODO) generated by experGen suite of tools for use in driver script -------

rm(list=ls())

#--------------predictor and target variable names--------#
	predictor.vars <- c("tasmax")
	target.var <- "tasmax"
#--------------grid region, mask settings----------#
        grid <- 'SCCSC0p1'  #grid resolution
        spat.mask.dir_1 <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/geomasks/red_river_0p1/OneD/'
        spat.mask.var <- 'red_river_0p1_masks'
#--------------- I,J settings ----------------#
        file.j.range <- 'J31-170'
        i.file <- 300  #file suffix  
        i.start <- 1
        j.start <- 31
        j.end <-  170
        loop.start <-  1 #j.start - (j.start-1)
        loop.end <-72 #  j.end - (j.start-1)
#------------ historical predictor(s)----------# 
	hist.file.start.year_1 <- 1961
	hist.file.end.year_1 <- 2005
	hist.train.start.year_1 <- 1961
	hist.train.end.year_1 <- 2005
	hist.scenario_1 <-'historical_r1i1p1'
	hist.nyrtot_1 <- (hist.train.end.year_1 - hist.train.start.year_1) + 1
	hist.model_1 <- 'MPI-ESM-LR' 
	hist.freq_1 <- 'day'
	hist.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING/GCM_DATA/CMIP5/MPI-ESM-LR/historical/atmos/day/r1i1p1/v20111006/tasmax/SCCSC0p1/OneD/'
##CEW edit: need time window specifications
hist.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_19610101-20051231.nc'
#------------ future predictor(s) -------------# 
	fut.file.start.year_1 <- 2006
	fut.file.end.year_1 <- 2100
        fut.train.start.year_1 <- 2006
        fut.train.end.year_1 <- 2100
	fut.scenario_1 <-'rcp85_r1i1p1'
	fut.nyrtot_1 <- (fut.train.end.year_1 - fut.train.start.year_1) + 1
	fut.model_1 <- 'MPI-ESM-LR'
	fut.freq_1 <- 'day'
	fut.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING/GCM_DATA/CMIP5/MPI-ESM-LR/rcp85/atmos/day/r1i1p1/v20111014/tasmax/SCCSC0p1/OneD/'
##CEW edit: 
fut.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_20060101-20991231.nc'
#------------- target -------------------------# 
	target.file.start.year_1 <- 1961
	target.file.end.year_1 <- 2011
        target.train.start.year_1 <- 1961
        target.train.end.year_1 <- 2011
	target.scenario_1 <- 'historical_r0i0p0'
	target.nyrtot_1 <- (target.train.end.year_1 - target.train.start.year_1) + 1 
	target.model_1 <-'livneh'
	target.freq_1 <- 'day'
        target.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING/OBS_DATA/GRIDDED_OBS/livneh/historical/atmos/day/r0i0p0/v1p2/tasmax/SCCSC0p1/OneD/'
##CEW edit: 
target.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_19610101-20051231.nc'
#------------- method name k-fold specs-----------------------#
	ds.method <- 'CDFtv1'
	ds.experiment <- 'vanilla-GFDL-CDFtv1-A00B00X00' #TODO Construct this outside of R
	k.fold <- 0
#-------------- output -----------------------#
	output.dir <- '/nbhome/a1r/PROJECTS/DOWNSCALING/3ToTheFifth/'
#TODO include standardize output dir for experiment A - in experGen 
#TO DO Custom Method Specific Params
#Sample only 
	lopt.wetday <- FALSE
	opt.transform <- 0
        npas <- 100  #Number of "cuts" for which quantiles will be empirically estimated (Default is 100 in CDFt package).

################### others ###################################
#---------------- reference to go in globals ----------------------------------- 
	configURL <-' Ref:http://gfdl.noaa.gov/esd_experiment_configs'

# ------ Set FUDGE environment ---------------
	FUDGEROOT = Sys.getenv(c("FUDGEROOT"))
	print(paste("FUDGEROOT is now activated:",FUDGEROOT,sep=''))
################ call main driver ###################################
print(paste("START TIME:",Sys.time(),sep=''))
#source(paste(FUDGEROOT,'Rsuite/drivers/','CDFt','/driverv2.R',sep=''))
source(paste(FUDGEROOT,'Rsuite/drivers/','CDFt','/driverv2.1.R',sep=''))
