#!/bin/tcsh
#PBS -S /bin/tcsh
#PBS -l nodes=1:ppn=2,walltime=12:00:00
#PBS -r y
#PBS -j oe
#PBS -N fudge_postProc
#PBS -E
#PBS -o <LOGDIR>/fudge_postProc_.m${MOAB_JOBNAME}.${MOAB_JOBID}
#PBS -q batch

	echo "Setting FUDGE environment.."
	# If a1r/cew is testing from a non-esd module, change the following for testing only
  
	module use -a /home/esd/local/modulefiles/
	module load <BRANCH> 
	##################
source <POSTPROC_CMD>

