#!/bin/tcsh 

source $BASEDIR/utils/bin/init 
#Establish arguments
set outdir = $1
set runcode = $2
set logfile = $3
mkdir -p $TMPDIR/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/geomasks/red_river_0p1/OneD/
mkdir -p $TMPDIR/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks
gcp --sync -cd /archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_19610101-20051231.nc $TMPDIR/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/
mkdir -p $TMPDIR/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks
gcp --sync -cd /archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_19610101-20051231.nc $TMPDIR/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/
mkdir -p $TMPDIR/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks
gcp --sync -cd /archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_20060101-20991231.nc $TMPDIR/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/

#Okay, these mkdirs and the corresponding GCPs are probably going to require hand editing

#Obs dataset
mkdir -p $TMPDIR/archive/esd/PROJECTS/DOWNSCALING///OBS_DATA/GRIDDED_OBS//livneh/historical//atmos/day/r0i0p0/v1p2/<var>/SCCSC0p1/OneD//
#Historic predictor dataset
mkdir -p $TMPDIR/archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//MPI-ESM-LR/historical//atmos/day/r1i1p1/v20111006/<var>/SCCSC0p1/OneD//
#Future dataset
mkdir -p $TMPDIR/archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//MPI-ESM-LR/<scenario>//atmos/day/r1i1p1/v20111014/<var>/SCCSC0p1/OneD//

gcp --sync -cd /archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/geomasks/red_river_0p1/OneD//*I<lonval>_J31-170.nc $TMPDIR/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/geomasks/red_river_0p1/OneD//
gcp -cd /archive/esd/PROJECTS/DOWNSCALING///OBS_DATA/GRIDDED_OBS//livneh/historical/dat/atmos/day/r0i0p0/v1p2/<var>/SCCSC0p1/OneD///*19610101-20051231.I<lonval>_J31-170.nc $TMPDIR/archive/esd/PROJECTS/DOWNSCALING///OBS_DATA/GRIDDED_OBS//livneh/historical//atmos/day/r0i0p0/v1p2/<var>/SCCSC0p1/OneD///
gcp -cd /archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//MPI-ESM-LR/historical/day/atmos/day/r1i1p1/v20111006/<var>/SCCSC0p1/OneD///*19610101-20051231.I<lonval>_J31-170.nc $TMPDIR/archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//MPI-ESM-LR/historical//atmos/day/r1i1p1/v20111006/<var>/SCCSC0p1/OneD///
gcp -cd /archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//MPI-ESM-LR/<scenario>/dat/atmos/day/r1i1p1/v20111014/<var>/SCCSC0p1/OneD///*20060101-20991231.I<lonval>_J31-170.nc $TMPDIR/archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//MPI-ESM-LR/<scenario>//atmos/day/r1i1p1/v20111014/<var>/SCCSC0p1/OneD///

#This probably is not neccessary, but the next line probably is
mkdir -p $TMPDIR/$outdir

R --vanilla < $runcode &>> $logfile &
wait 
set dsout = `tail $logfile | grep -oP "Downscaled output file:\K.*"`
#Copy output to /archive, like a responsible person
gcp -cd $TMPDIR/$dsout $dsout

