#'Applies temporal masks to a one-dimensional dataset, presumably generated by TrainDriver.
#'At some point in the future, mask should be able to be a) a timeseries of the same
#'length, b) a shorter (365-day) timseries, c) a longer, subsettable timeseries.
#'For now, it should be enough to get the 
#' @param data: a vector representing a timeseries
#' @param mask: a vector of NAs and 1's representing a mask. Needs to be of the same dimensions as the data.
#' @return A vector of the same dimensions as data with NAs in all places where the mask contained NA.
#' @example insert example here
#' @references \url{link to the FUDGE API documentation}
#' 
#'  
#' CEW 8-15-14 revision: 
#' Given current state of DownscaleBySeason, revising to assume 1-D input data of length timeaxis.
#' The check is being replaced with a check on the first date in the timeseries of the original file.
#' Will probably revisit this later. This means removing timeData as well, BTW. 
#' CEW 8-24-14 revision: 
#' Adding checks on the mask agreement/other stuff to MaskQC function, to be called before applying
#' anything here. Also, extending functionality to apply kfold masks as well. 
ApplyTemporalMask<-function(data, mask){
  
  data.length<-length(data)
  mask.length <- length(mask)
  if ( data.length != mask.length ){
    print(summary(data))
    stop(paste("Mask dimension error: Data had length of", data.length,
               "while time mask had length of", mask.length))
  }
      tempvar <- data * mask
      return(tempvar)
}
