########Input R parameters generated by experGen suite of tools for use in driver script -------
rm(list=ls())

#--------------predictor and target variable names--------#
	predictor.vars <- 'tasmax' 
	target.var <- 'tasmax'
#--------------grid region, mask settings----------#
        grid <- 'SCCSC0p1' 
        spat.mask.dir_1 <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/geomasks/red_river_0p1/OneD/' 
        spat.mask.var <- 'red_river_0p1_masks' 
	ds.region <- 'RR'
#--------------- I,J settings ----------------#
        file.j.range <- 'J31-170' 
        i.file <- 275   
        j.start <- 31 
        j.end <- 170 
        loop.start <-  j.start - (j.start-1)
        loop.end <-  j.end - (j.start-1)
#------------ historical predictor(s)----------# 
	hist.file.start.year_1 <- 19610101 
	hist.file.end.year_1 <- 20051231
        hist.train.start.year_1 <- 19610101
	hist.train.end.year_1 <- 20051231 
	hist.scenario_1 <- 'historical_r1i1p1'
	hist.nyrtot_1 <- (hist.train.end.year_1 - hist.train.start.year_1) + 1
	hist.model_1 <- 'MPI-ESM-LR' 
	hist.freq_1 <- 'day' 
	hist.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING//GCM_DATA/CMIP5//MPI-ESM-LR/historical/day/atmos/day/r1i1p1/v20111006/tasmax/SCCSC0p1/OneD/' 
	hist.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_19610101-20051231.nc' 
#------------ future predictor(s) -------------# 
	fut.file.start.year_1 <- 20060101 
	fut.file.end.year_1 <- 20991231 
        fut.train.start.year_1 <- 20060101 
        fut.train.end.year_1 <- 20991231 
	fut.scenario_1 <- 'rcp45_r1i1p1'
	fut.nyrtot_1 <- (fut.train.end.year_1 - fut.train.start.year_1) + 1
	fut.model_1 <- 'MPI-ESM-LR' 
	fut.freq_1 <- 'day' 
	fut.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING//GCM_DATA/CMIP5//MPI-ESM-LR/rcp45/day/atmos/day/r1i1p1/v20111006/tasmax/SCCSC0p1/OneD/'
	fut.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_20060101-20991231.nc'
        fut.time.trim.mask <- 'na'
#------------- target -------------------------# 
	target.file.start.year_1 <- 19610101 
	target.file.end.year_1 <- 20051231 
        target.train.start.year_1 <- 19610101 
        target.train.end.year_1 <- 20051231 
	target.scenario_1 <- 'historical_r0i0p0'
	target.nyrtot_1 <- (target.train.end.year_1 - target.train.start.year_1) + 1 
	target.model_1 <- 'livneh'
	target.freq_1 <- 'day' 
        target.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING//OBS_DATA/GRIDDED_OBS//livneh/historical/day/atmos/day/r0i0p0/v1p2/tasmax/SCCSC0p1/OneD/'
	target.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_19610101-20051231.nc'
#------------- method name k-fold specs-----------------------#
        ds.method <- 'CDFt' 
	#ds.experiment <- 'RRtxp1-CDFt-C34atTestL01K00' 
	ds.experiment <- "DC_test2"
	k.fold <- 0 
	
#-------------- output -----------------------#
	output.dir <- '<OUTPUT_DIR>'
	mask.output.dir <- '<OUTPUT_DIR>' 
#-------------  custom -----------------------#
        args=list(dev=1,npas='default') 
 #Number of "cuts" for which quantiles will be empirically estimated (Default is 100 in CDFt package).
#-------------- pp ---------------------------#
        mask.list <- list(mask1=list(type='SBiasCorr',adjust.out='off',qc.mask='on',qc_options=list(botlim=-6.,toplim=6.)))
################### others ###################################
#---------------- reference to go in globals ----------------------------------- 
	configURL <-' Ref:http://gfdl.noaa.gov/esd_experiment_configs'
# ------ Set FUDGE environment ---------------
#	FUDGEROOT = Sys.getenv(c("FUDGEROOT"))
	FUDGEROOT <- '/home/cew/Code/fudge2014/'
	print(paste("FUDGEROOT is now activated:",FUDGEROOT,sep=''))
	BRANCH <- 'undefined'
################ call main driver ###################################
print(paste("START TIME:",Sys.time(),sep=''))

#----------Use /vftmp as necessary---------------# 
TMPDIR = Sys.getenv(c("TMPDIR"))
if (TMPDIR == ""){
  stop("ERROR: TMPDIR is not set. Please set it and try it") 
  }
#########################################################################
gcp_to_TMPDIR <- function(TMPDIR, directory, file.str=""){
  if((grepl('^/archive',directory)) | (grepl('^/work',directory))){
    directory.tmp <- paste(TMPDIR,directory,sep='')
	if(file.str!="") file.str=paste("/*",file.str, sep="")
	file.tmp <- paste(directory.tmp, file.str, sep="") 
	message(file.tmp)
    if(!file.exists(file.tmp)){
      #Gcp should already be loaded by setenv_fudge or the module if you are running this
      if(system('gcp --version')!=0){
        loadstr = 'source /usr/share/Modules/init/sh;module load gcp;'
      }else{
        loadstr = ""
      }
      commandstr <- paste(loadstr, "gcp -cd", paste(directory,file.str, sep=""), directory.tmp)
      sys.status <- system(commandstr)
      if (sys.status!=0){
        warning(paste("Error in gcp_to_TMPDIR; exited with status", sys.status, "; returning orig file"))
        return(directory)
      }
    }
    return(directory.tmp)
  }else{
    return(directory)
  }
}

ijstr <- paste("I", i.file, "_", file.j.range, ".nc", sep="")
if(spat.mask.dir_1 != 'na'){
spat.mask.dir_1 <- gcp_to_TMPDIR(TMPDIR, spat.mask.dir_1, ijstr)}
if(hist.indir_1 != 'na'){
hist.indir_1 <- gcp_to_TMPDIR(TMPDIR,  hist.indir_1, ijstr)}
if(fut.indir_1 != 'na'){
fut.indir_1 <- gcp_to_TMPDIR(TMPDIR, fut.indir_1, ijstr)}
if(target.indir_1 != 'na'){
target.indir_1 <- gcp_to_TMPDIR(TMPDIR, target.indir_1, ijstr)}
if(target.time.window != 'na'){
target.time.window <- gcp_to_TMPDIR(TMPDIR, target.time.window)}
if(hist.time.window != 'na'){
hist.time.window <- gcp_to_TMPDIR(TMPDIR, hist.time.window)}
if(fut.time.window != 'na'){
fut.time.window <- gcp_to_TMPDIR(TMPDIR, fut.time.window)}
if(fut.time.trim.mask != 'na'){
fut.time.trim.mask <- gcp_to_TMPDIR(TMPDIR, fut.time.trim.mask)}
##Check for output and need to gcp on here as well
#If file exists in TMPDIR, was presumably created by the runscript and no GCP needed in R
#output.dir <- paste(TMPDIR,output.dir,sep='')
#mask.output.dir <- paste(TMPDIR,mask.output.dir,sep='')
#output.dir <- gcp_to_TMPDIR(TMPDIR, output.dir)
#mask.output.dir <- gcp_to_TMPDIR(TMPDIR,mask.output.dir)

#output.dir and mask.output.dir should already contain /TMPDIR
#in the output path structure

#########################################################################
#-------------------------------------------------#
#source(paste(FUDGEROOT,'Rsuite/Drivers/',ds.method,'/Driver_',ds.method,'.R',sep=''))
source(paste(FUDGEROOT,'Rsuite/Drivers/','Master_Driver.R',sep=''))
