#Modified by CEW 8-25: adding temporal masks for time windowing function
#In future, esdgen time window would go under esdgen data; at this point, however, masks 
#are just for k=0 and we can get by on one

########Input R parameters(TODO) generated by experGen suite of tools for use in driver script -------

rm(list=ls())

############### Section 1 ######################
	predictor.var <- "tasmax"
	predictand.var <- "tasmax"
#------------ historical predictor(s)----------# 
	hist.start.year_1 <- 1961
	hist.end.year_1 <- 2005
	hist.scenario_1 <-'historical_r1i1p1'
	hist.nyrtot_1 <- (hist.end.year_1 - hist.start.year_1) + 1
	hist.model_1 <- 'MPI-ESM-LR' 
	hist.freq_1 <- 'day'
	hist.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING/GCM_DATA/CMIP5/MPI-ESM-LR/historical/atmos/day/r1i1p1/v20111006/tasmax/SCCSC0p1/OneD/'
	spat.mask.dir_1 <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/geomasks/OneD/'
	spat.mask.var <- 'red_river_0p1_masks'
##CEW edit: 
  hist.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_19610101-20051231.nc'
#------------ future predictor(s) -------------# 
	fut.start.year_1 <- 2006
	fut.end.year_1 <- 2099
	fut.scenario_1 <-'rcp85.r1i1p1'
	fut.nyrtot_1 <- (fut.end.year_1 - fut.start.year_1) + 1
	fut.model_1 <- 'MPI-ESM-LR'
	fut.freq_1 <- 'day'
	fut.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING/GCM_DATA/CMIP5/MPI-ESM-LR/rcp85/atmos/day/r1i1p1/v20111014/tasmax/SCCSC0p1/OneD/'
	fut.spatial.mask_1 <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/geomasks/red_river_0p1_masks.nc'
##CEW edit: 
  fut.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_20060101-20991231.nc'

#------------- target -------------------------# 
	target.start.year_1 <- 1961
	target.end.year_1 <- 2005
	target.scenario_1 <- 'historical'
	target.nyrtot_1 <- (target.end.year_1 - target.start.year_1) + 1 
	target.model_1 <-'livneh'
	target.freq_1 <- 'day'
        target.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING/OBS_DATA/GRIDDED_OBS/livneh/historical/atmos/day/r0i0p0/v1p2/tasmax/SCCSC0p1/OneD/'
	target.spatial.mask_1 <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/geomasks/red_river_0p1_masks.nc'
##CEW edit: 
  target.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/3ToThe5th/masks/timemasks/maskdays_bymonth_19610101-20051231.nc'

############### Section 2 #######################
#------------- method name k-fold specs-----------------------#
	#ds.method <- 'CDFtv1'
ds.method <- 'CDFt'
	ds.experiment <- 'vanilla-GFDL-CDFtv1-A00B00X00'
	k.fold <- 0
#-------------- output -----------------------#
	output.dir <- '/nbhome/a1r/PROJECTS/DOWNSCALING/3ToTheFifth/'
#--------------grid region settings----------#
	region <- 'sccsc0p1'
#--------------- I,J settings ----------------#
	file.j.range <- 'J31-170' 
	i.start <- 300 
	i.end <- 300 
	j.start <- 32 - 31
	j.end <-  170 - 30 
################## Section 3 #######################
#TO DO Custom Method Specific Params
	lopt.wetday <- FALSE
	opt.transform <- 0
################### others ###################################
#---------------- reference ----------------------------------- 
	configURL <-' .Ref:http://gfdl.noaa.gov/esd_experiment_configs'

# ------ Set FUDGE environment ---------------
	FUDGEROOT = Sys.getenv(c("FUDGEROOT"))
	print(paste("FUDGEROOT is now activated:",FUDGEROOT,sep=''))
################ call main driver ###################################

source(paste(FUDGEROOT,'Rsuite/drivers/','driverv2.R',sep=''))
