########Input R parameters generated by experGen suite of tools for use in driver script -------
rm(list=ls())

#--------------predictor and target variable names--------#
predictor.vars <- 'pr' 
target.var <- 'pr'
#--------------grid region, mask settings----------#
grid <- 'US48' 
spat.mask.dir_1 <- 'na' 
spat.mask.var <- 'na' 
ds.region <- 'na'
#--------------- I,J settings ----------------#
file.j.range <- 'J454-567' 
i.file <- 800   
j.start <- 454 
j.end <- 567 
loop.start <-  j.start - (j.start-1)
loop.end <-  j.end - (j.start-1)
#------------ historical predictor(s)----------# 
hist.file.start.year_1 <- 1979 
hist.file.end.year_1 <- 2008
hist.train.start.year_1 <- 1979
hist.train.end.year_1 <- 2008 
hist.scenario_1 <- 'amip_r1i1p1'
hist.nyrtot_1 <- (hist.train.end.year_1 - hist.train.start.year_1) + 1
hist.model_1 <- 'GFDL-HIRAM-C360-COARSENED' 
hist.freq_1 <- 'day' 
hist.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING///NCPP2013/modified/NOAA-GFDL/GFDL-HIRAM-C360-COARSENED/amip/day/atmos/day/r1i1p1/v20110601/pr/OneD/' 
#hist.time.window <- 'na' 
hist.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/PerfectModel/masks/timemasks/maskdays_bymonth_19790101-20081231.nc'
#------------ future predictor(s) -------------# 
fut.file.start.year_1 <- 2086 
fut.file.end.year_1 <- 2095 
fut.train.start.year_1 <- 2086 
fut.train.end.year_1 <- 2095 
fut.scenario_1 <- 'sst2090_r1i1p1'
fut.nyrtot_1 <- (fut.train.end.year_1 - fut.train.start.year_1) + 1
fut.model_1 <- 'GFDL-HIRAM-C360-COARSENED' 
fut.freq_1 <- 'day' 
fut.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING///NCPP2013/modified/NOAA-GFDL/GFDL-HIRAM-C360-COARSENED/sst2090/day/atmos/day/r1i1p1/v20110601/pr/OneD/'
#fut.time.window <- 'na'
fut.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/PerfectModel/masks/timemasks/maskdays_bymonth_20860101-20951231.nc'
fut.time.trim.mask <- 'na'
#------------- target -------------------------# 
target.file.start.year_1 <- 1979 
target.file.end.year_1 <- 2008 
target.train.start.year_1 <- 1979 
target.train.end.year_1 <- 2008 
target.scenario_1 <- 'amip_r1i1p1'
target.nyrtot_1 <- (target.train.end.year_1 - target.train.start.year_1) + 1 
target.model_1 <- 'GFDL-HIRAM-C360'
target.freq_1 <- 'day' 
target.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING///NCPP2013/modified/NOAA-GFDL/GFDL-HIRAM-C360/amip/day/atmos/day/r1i1p1/v20110601/pr/OneD/'
#target.time.window <- 'na'
target.time.window <- '/archive/esd/PROJECTS/DOWNSCALING/PerfectModel/masks/timemasks/maskdays_bymonth_19790101-20081231.nc'
#------------- method name k-fold specs-----------------------#
#ds.method <- 'DeltaSD' 
ds.method <- 'CDFt'
ds.experiment <- 'PMprp1-CDFt-A18-pr-bugfix4' #DO NOT CHANGE WHILE TESTING IN multi_pp_opts
k.fold <- 0 
#pr_opts=list(pr_threshold_in='us_trace',pr_freqadj_in='on',pr_conserve_in='on',pr_threshold_out='us_trace',pr_conserve_out='off')
#-------------- output -----------------------#
output.dir <- '/home/cew/Code/testing/'
mask.output.dir <- '/home/cew/Code/testing/' 
#-------------  custom -----------------------#
#args=list(deltaop='ratio',deltatype='median', keep.zeroes=TRUE) 
args=list(npas=0,dev=2)
#Number of "cuts" for which quantiles will be empirically estimated (Default is 100 in CDFt package).
#-------------- pp ---------------------------#
# pre_ds = list(mask1=list(type='PR', var='pr', loc='outloop', 
#                          pp.args=list(thold='us_trace',freqadj='on',conserve='on')))
# post_ds = list(mask1=list(type='PR', qc.mask='off', adjust.out='on', loc='outloop', 
#                          qc_args=list(thold='us_trace', conserve='off')) #,
#               #mask2=list(type='flag.neg',adjust.out='off',qc.mask='on', loc='inloop',
#                #          qc_options=list('na'))
#           )
pr_opts=list(pr_threshold_in='us_trace',pr_freqadj_in='off',pr_conserve_in='on',
             pr_threshold_out='zero',pr_conserve_out='on', #'us_trace'
             apply_0_mask='on')
#mask.list <- list(mask1=list(type='flag.neg',adjust.out='off',qc.mask='on',qc_options=list('na')))
mask.list <- list('na')
###Note that the above section CURRENTLY DOES NOT WORK! There is a check for a 
###argument named propts later that only gets added if the adaptation function is invoked!

################### others ###################################
#---------------- reference to go in globals ----------------------------------- 
configURL <-' Ref:http://gfdl.noaa.gov/esd_experiment_configs'
# ------ Set FUDGE environment ---------------
#	FUDGEROOT = Sys.getenv(c("FUDGEROOT"))
FUDGEROOT <- '/home/cew/Code/fudge2014/'
print(paste("FUDGEROOT is now activated:",FUDGEROOT,sep=''))
BRANCH <- 'undefined'
################ call main driver ###################################
print(paste("START TIME:",Sys.time(),sep=''))

#----------Use /vftmp as necessary---------------# 
TMPDIR = ""
# if (TMPDIR == ""){
#   stop("ERROR: TMPDIR is not set. Please set it and try it") 
#   }
#########################################################################
if((grepl('^/archive',spat.mask.dir_1)) | (grepl('^/work',spat.mask.dir_1))){
  spat.mask.dir_1 <- paste(TMPDIR,spat.mask.dir_1,sep='')
}
if((grepl('^/archive',hist.indir_1)) | (grepl('^/work',hist.indir_1))){
  hist.indir_1 <- paste(TMPDIR,hist.indir_1,sep='')
}
if((grepl('^/archive',fut.indir_1)) | (grepl('^/work',fut.indir_1))){
  fut.indir_1 <- paste(TMPDIR,fut.indir_1,sep='')
}
if((grepl('^/archive',hist.indir_1)) | (grepl('^/work',hist.indir_1))){
  target.indir_1 <- paste(TMPDIR,target.indir_1,sep='')
}
if((grepl('^/archive',target.time.window)) | (grepl('^/work',target.time.window))){
  target.time.window <- paste(TMPDIR,target.time.window,sep='')
}
if((grepl('^/archive',hist.time.window)) | (grepl('^/work',hist.time.window))){
  hist.time.window <- paste(TMPDIR,hist.time.window,sep='')
}
if((grepl('^/archive',fut.time.window)) | (grepl('^/work',fut.time.window))){
  fut.time.window <- paste(TMPDIR,fut.time.window,sep='')
}
if(fut.time.trim.mask != 'na'){
  if((grepl('^/archive',fut.time.trim.mask)) | (grepl('^/work',fut.time.trim.mask))){
    fut.time.trim.mask <- paste(TMPDIR,fut.time.trim.mask,sep='')
  }
}
output.dir <- paste(TMPDIR,output.dir,sep='')
mask.output.dir <- paste(TMPDIR,mask.output.dir,sep='')

#########################################################################
#-------------------------------------------------#
#source(paste(FUDGEROOT,'Rsuite/Drivers/',ds.method,'/Driver_',ds.method,'.R',sep=''))

source(paste(FUDGEROOT,'Rsuite/Drivers/','Master_Driver.R',sep=''))
