########Input R parameters generated by experGen suite of tools for use in driver script -------
rm(list=ls())

#--------------predictor and target variable names--------#
	predictor.vars <- 'tasmaxAnom' 
	target.var <- 'tasmaxAnom'
#--------------grid region, mask settings----------#
        grid <- 'US48' 
        spat.mask.dir_1 <- 'na' 
        spat.mask.var <- 'na' 
	ds.region <- 'US48'
#--------------- I,J settings ----------------#
        file.j.range <- 'J454-567' 
        i.file <- 748   
        j.start <- 454 
        j.end <- 567 
        loop.start <-  j.start - (j.start-1)
        loop.end <-  j.end - (j.start-1)
#------------ historical predictor(s)----------# 
	hist.file.start.year_1 <- 1979 
	hist.file.end.year_1 <- 2008
        hist.train.start.year_1 <- 1979
	hist.train.end.year_1 <- 2008 
	hist.scenario_1 <- 'amip_r1i1p1'
	hist.nyrtot_1 <- (hist.train.end.year_1 - hist.train.start.year_1) + 1
	hist.model_1 <- 'BOGUS' 
	hist.freq_1 <- 'day' 
	hist.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//BOGUS/amip/day/atmos/anomSbx7C360LR/r1i1p1/v1/tasmaxAnom/US48/OneD/' 
	hist.time.window <- 'na' 
#------------ future predictor(s) -------------# 
	fut.file.start.year_1 <- 1979 
	fut.file.end.year_1 <- 2008 
        fut.train.start.year_1 <- 1979 
        fut.train.end.year_1 <- 2008 
	fut.scenario_1 <- 'amip_r1i1p1'
	fut.nyrtot_1 <- (fut.train.end.year_1 - fut.train.start.year_1) + 1
	fut.model_1 <- 'BOGUS' 
	fut.freq_1 <- 'day' 
	fut.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//BOGUS/amip/day/atmos/anomSbx7C360LR/r1i1p1/v1/tasmaxAnom/US48/OneD/'
	fut.time.window <- 'na'
        fut.time.trim.mask <- 'na'
#------------- target -------------------------# 
	target.file.start.year_1 <- 1979 
	target.file.end.year_1 <- 2008 
        target.train.start.year_1 <- 1979 
        target.train.end.year_1 <- 2008 
	target.scenario_1 <- 'amip_r1i1p1'
	target.nyrtot_1 <- (target.train.end.year_1 - target.train.start.year_1) + 1 
	target.model_1 <- 'BOGUS'
	target.freq_1 <- 'day' 
        target.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//BOGUS/amip/day/atmos/anomSbx7C360LR/r1i1p1/v1/tasmaxAnom/US48/OneD/'
	target.time.window <- 'na'
#------------- method name k-fold specs-----------------------#
        ds.method <- 'DeltaSD' 
	ds.experiment <- 'PMtasmaxAnomp1-DeltaSD-AXXq-aL01-test2K00' 
	k.fold <- 0 
	
#-------------- output -----------------------#
	output.dir <- '/home/cew/Code/testing/'
	mask.output.dir <- '/home/cew/Code/testing/'
#-------------  custom -----------------------#
        args=list(deltatype='median',deltaop='add') 
 #Number of "cuts" for which quantiles will be empirically estimated (Default is 100 in CDFt package).
#-------------- pp ---------------------------#
        mask.list <- "na"
################### others ###################################
#---------------- reference to go in globals ----------------------------------- 
	configURL <-' Ref:http://gfdl.noaa.gov/esd_experiment_configs'
# ------ Set FUDGE environment ---------------
#	FUDGEROOT = Sys.getenv(c("FUDGEROOT"))
	FUDGEROOT <- '/home/cew/Code/fudge2014/'
	print(paste("FUDGEROOT is now activated:",FUDGEROOT,sep=''))
	BRANCH <- 'undefined'
################ call main driver ###################################
print(paste("START TIME:",Sys.time(),sep=''))

#----------Use /vftmp as necessary---------------# 
TMPDIR = ""
# if (TMPDIR == ""){
#   stop("ERROR: TMPDIR is not set. Please set it and try it") 
#   }
#########################################################################
if(spat.mask.dir_1 != 'na'){
if((grepl('^/archive',spat.mask.dir_1)) | (grepl('^/work',spat.mask.dir_1))){
spat.mask.dir_1 <- paste(TMPDIR,spat.mask.dir_1,sep='')
}}
if(hist.indir_1 != 'na'){
if((grepl('^/archive',hist.indir_1)) | (grepl('^/work',hist.indir_1))){
hist.indir_1 <- paste(TMPDIR,hist.indir_1,sep='')
}}
if(fut.indir_1 != 'na'){
if((grepl('^/archive',fut.indir_1)) | (grepl('^/work',fut.indir_1))){
fut.indir_1 <- paste(TMPDIR,fut.indir_1,sep='')
}}
if(hist.indir_1 != 'na'){
if((grepl('^/archive',hist.indir_1)) | (grepl('^/work',hist.indir_1))){
target.indir_1 <- paste(TMPDIR,target.indir_1,sep='')
}}
if(target.time.window != 'na'){
if((grepl('^/archive',target.time.window)) | (grepl('^/work',target.time.window))){
target.time.window <- paste(TMPDIR,target.time.window,sep='')
}}
if(hist.time.window != 'na'){
if((grepl('^/archive',hist.time.window)) | (grepl('^/work',hist.time.window))){
hist.time.window <- paste(TMPDIR,hist.time.window,sep='')
}}
if(fut.time.window != 'na'){
if((grepl('^/archive',fut.time.window)) | (grepl('^/work',fut.time.window))){
fut.time.window <- paste(TMPDIR,fut.time.window,sep='')
}}
if(fut.time.trim.mask != 'na'){
if((grepl('^/archive',fut.time.trim.mask)) | (grepl('^/work',fut.time.trim.mask))){
fut.time.trim.mask <- paste(TMPDIR,fut.time.trim.mask,sep='')
}
}
output.dir <- paste(TMPDIR,output.dir,sep='')
mask.output.dir <- paste(TMPDIR,mask.output.dir,sep='')

#########################################################################
#-------------------------------------------------#
#source(paste(FUDGEROOT,'Rsuite/Drivers/',ds.method,'/Driver_',ds.method,'.R',sep=''))
source(paste(FUDGEROOT,'Rsuite/Drivers/','Master_Driver.R',sep=''))
