########Input R parameters generated by experGen suite of tools for use in driver script -------
rm(list=ls())

#--------------predictor and target variable names--------#
	predictor.vars <- 'tasmax' 
	target.var <- 'tasmax'
#--------------grid region, mask settings----------#
        #grid <- 'US48' 
grid <- 'SCCSC0p1' 
        spat.mask.dir_1 <- 'na' 
        spat.mask.var <- 'US48_masks' 
#	ds.region <- 'US48'
ds.region <- 'RR'
#--------------- I,J settings ----------------#
file.j.range <- 'J31-170' 
i.file <- 300   
j.start <- 31 
j.end <- 170 
loop.start <-  j.start - (j.start-1)
loop.end <-  j.end - (j.start-1)
#         file.j.range <- 'J454-567' 
#         i.file <- 800   
#         j.start <- 454 
#         j.end <- 567 
#         loop.start <-  j.start - (j.start-1)
#         loop.end <-  j.end - (j.start-1)
#------------ historical predictor(s)----------# 
hist.file.start.year_1 <- 1961 
hist.file.end.year_1 <- 2005
hist.train.start.year_1 <- 1961
hist.train.end.year_1 <- 2005 
hist.scenario_1 <- 'historical_r1i1p1'
hist.nyrtot_1 <- (hist.train.end.year_1 - hist.train.start.year_1) + 1
hist.model_1 <- 'MPI-ESM-LR' 
hist.freq_1 <- 'day' 
#	hist.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//MPI-ESM-LR/historical//atmos/day/r1i1p1/v20111006/tasmax/SCCSC0p1/OneD/'
hist.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//MPI-ESM-LR/historical//atmos/day/r1i1p1/v20111006/tasmax/SCCSC0p1/OneD/'
hist.time.window <- 'na' 
#------------ future predictor(s) -------------# 
fut.file.start.year_1 <- 2006 
fut.file.end.year_1 <- 2099 
fut.train.start.year_1 <- 2006 
fut.train.end.year_1 <- 2099 
fut.scenario_1 <- 'rcp85_r1i1p1'
fut.nyrtot_1 <- (fut.train.end.year_1 - fut.train.start.year_1) + 1
fut.model_1 <- 'MPI-ESM-LR' 
fut.freq_1 <- 'day' 
fut.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING///GCM_DATA/CMIP5//MPI-ESM-LR/rcp85//atmos/day/r1i1p1/v20111014/tasmax/SCCSC0p1/OneD/'
fut.time.window <- 'na'
fut.time.trim.mask <- 'na'
#------------- target -------------------------# 
target.file.start.year_1 <- 1961 
target.file.end.year_1 <- 2005 
target.train.start.year_1 <- 1961 
target.train.end.year_1 <- 2005 
target.scenario_1 <- 'historical_r0i0p0'
target.nyrtot_1 <- (target.train.end.year_1 - target.train.start.year_1) + 1 
target.model_1 <- 'livneh'
target.freq_1 <- 'day' 
target.indir_1 <- '/archive/esd/PROJECTS/DOWNSCALING///OBS_DATA/GRIDDED_OBS//livneh/historical//atmos/day/r0i0p0/v1p2/tasmax/SCCSC0p1/OneD/'
target.time.window <- 'na'
#------------- method name k-fold specs-----------------------#
        #ds.method <- 'DeltaSD' 
#ds.method <- 'EDQM'
ds.method <- 'EDQMv2'
#ds.method <- 'EDQMv3'
	ds.experiment <- paste('PMtx1-', ds.method, '-A18hX01K00', sep="")
	k.fold <- 0 
#	pr_opts=list(pr_threshold_in='us_trace',pr_freqadj_in='off',pr_conserve_in='on',pr_threshold_out='us_trace',pr_conserve_out='on')
#-------------- output -----------------------#
	output.dir <- '/home/cew/Code/testing/'
	mask.output.dir <- '/home/cew/Code/testing/' 
#-------------  custom -----------------------#
        #args=list(deltaop='add',deltatype='median') 
#args=list('npas'=0,'dev'=1)
args=list('na')
 #Number of "cuts" for which quantiles will be empirically estimated (Default is 100 in CDFt package).
#-------------- pp ---------------------------#
#        mask.list <- list(mask1=list(type='flag.neg',adjust.out='off',qc.mask='on',qc_options=list('na')))
mask.list <- list('na')
################### others ###################################
#---------------- reference to go in globals ----------------------------------- 
	configURL <-' Ref:http://gfdl.noaa.gov/esd_experiment_configs'
# ------ Set FUDGE environment ---------------
#	FUDGEROOT = Sys.getenv(c("FUDGEROOT"))
	FUDGEROOT <- '/home/cew/Code/fudge2014/'
	print(paste("FUDGEROOT is now activated:",FUDGEROOT,sep=''))
	BRANCH <- 'undefined'
################ call main driver ###################################
print(paste("START TIME:",Sys.time(),sep=''))

#----------Use /vftmp as necessary---------------# 
TMPDIR = ""
# if (TMPDIR == ""){
#   stop("ERROR: TMPDIR is not set. Please set it and try it") 
#   }
#########################################################################
if((grepl('^/archive',spat.mask.dir_1)) | (grepl('^/work',spat.mask.dir_1))){
spat.mask.dir_1 <- paste(TMPDIR,spat.mask.dir_1,sep='')
}
if((grepl('^/archive',hist.indir_1)) | (grepl('^/work',hist.indir_1))){
hist.indir_1 <- paste(TMPDIR,hist.indir_1,sep='')
}
if((grepl('^/archive',fut.indir_1)) | (grepl('^/work',fut.indir_1))){
fut.indir_1 <- paste(TMPDIR,fut.indir_1,sep='')
}
if((grepl('^/archive',hist.indir_1)) | (grepl('^/work',hist.indir_1))){
target.indir_1 <- paste(TMPDIR,target.indir_1,sep='')
}
if((grepl('^/archive',target.time.window)) | (grepl('^/work',target.time.window))){
target.time.window <- paste(TMPDIR,target.time.window,sep='')
}
if((grepl('^/archive',hist.time.window)) | (grepl('^/work',hist.time.window))){
hist.time.window <- paste(TMPDIR,hist.time.window,sep='')
}
if((grepl('^/archive',fut.time.window)) | (grepl('^/work',fut.time.window))){
fut.time.window <- paste(TMPDIR,fut.time.window,sep='')
}
if(fut.time.trim.mask != 'na'){
if((grepl('^/archive',fut.time.trim.mask)) | (grepl('^/work',fut.time.trim.mask))){
fut.time.trim.mask <- paste(TMPDIR,fut.time.trim.mask,sep='')
}
}
output.dir <- paste(TMPDIR,output.dir,sep='')
mask.output.dir <- paste(TMPDIR,mask.output.dir,sep='')

#########################################################################
#-------------------------------------------------#
#source(paste(FUDGEROOT,'Rsuite/Drivers/',ds.method,'/Driver_',ds.method,'.R',sep=''))
source(paste(FUDGEROOT,'Rsuite/Drivers/','Master_Driver.R',sep=''))
